// Generated by CoffeeScript 1.12.7
$.pjax.defaults.timeout = 3000;

$(document).pjax('a:not(.noajax)', '.container');

$(document).on('pjax:send', function() {
  $('.container').hide().empty();
  $('.preloader').show();
});

$(document).on('pjax:complete', function() {
  $('.container').fadeIn();
  $('.preloader').hide();
  allScript();
});

$('.left-column_nav_item a').on('click', function() {
  $('.left-column_nav_item').removeClass('left-column_nav_item_active');
  return $(this).parent().addClass('left-column_nav_item_active');
});

//# sourceMappingURL=index.js.map